# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{link2}
  s.version = "0.1.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jonas Grimfelt"]
  s.date = %q{2010-03-03}
  s.description = %q{Generation next link_to-helper for Rails: Spiced with intelligence, and semantic beauty.}
  s.email = %q{grimen@gmail.com}
  s.extra_rdoc_files = [
    "README.textile",
     "TODO"
  ]
  s.files = [
    "MIT-LICENSE",
     "README.textile",
     "Rakefile",
     "TODO",
     "generators/link2/link2_generator.rb",
     "generators/link2/templates/initializer.rb",
     "lib/link2.rb",
     "lib/link2/brain.rb",
     "lib/link2/helpers.rb",
     "lib/link2/i18n.rb",
     "lib/link2/locales/en.yml",
     "lib/link2/support.rb",
     "lib/link2/version.rb",
     "rails/init.rb"
  ]
  s.homepage = %q{http://github.com/grimen/link2}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Generation next link_to-helper for Rails: Spiced with intelligence, and semantic beauty.}
  s.test_files = [
    "test/brain_test.rb",
     "test/helpers_test.rb",
     "test/i18n_test.rb",
     "test/integration/helpers_integration_test.rb",
     "test/integration/rails_app/app/controllers/application_controller.rb",
     "test/integration/rails_app/app/controllers/home_controller.rb",
     "test/integration/rails_app/app/controllers/ponies_controller.rb",
     "test/integration/rails_app/app/helpers/application_helper.rb",
     "test/integration/rails_app/app/models/active_record/pony.rb",
     "test/integration/rails_app/config/boot.rb",
     "test/integration/rails_app/config/environment.rb",
     "test/integration/rails_app/config/environments/test.rb",
     "test/integration/rails_app/config/initializers/inflections.rb",
     "test/integration/rails_app/config/initializers/link2.rb",
     "test/integration/rails_app/config/initializers/new_rails_defaults.rb",
     "test/integration/rails_app/config/initializers/session_store.rb",
     "test/integration/rails_app/config/routes.rb",
     "test/link2_test.rb",
     "test/orm/active_record.rb",
     "test/support/assertions_helper.rb",
     "test/support/debug_helper.rb",
     "test/support/substitutions_helper.rb",
     "test/support/webrat_setup.rb",
     "test/support_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 2.3.0"])
      s.add_runtime_dependency(%q<actionpack>, [">= 2.3.0"])
      s.add_development_dependency(%q<test-unit>, ["= 1.2.3"])
      s.add_development_dependency(%q<mocha>, [">= 0.9.8"])
      s.add_development_dependency(%q<webrat>, [">= 0.7.0"])
      s.add_development_dependency(%q<leftright>, [">= 0.0.3"])
      s.add_development_dependency(%q<activerecord>, [">= 2.3.0"])
    else
      s.add_dependency(%q<activesupport>, [">= 2.3.0"])
      s.add_dependency(%q<actionpack>, [">= 2.3.0"])
      s.add_dependency(%q<test-unit>, ["= 1.2.3"])
      s.add_dependency(%q<mocha>, [">= 0.9.8"])
      s.add_dependency(%q<webrat>, [">= 0.7.0"])
      s.add_dependency(%q<leftright>, [">= 0.0.3"])
      s.add_dependency(%q<activerecord>, [">= 2.3.0"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 2.3.0"])
    s.add_dependency(%q<actionpack>, [">= 2.3.0"])
    s.add_dependency(%q<test-unit>, ["= 1.2.3"])
    s.add_dependency(%q<mocha>, [">= 0.9.8"])
    s.add_dependency(%q<webrat>, [">= 0.7.0"])
    s.add_dependency(%q<leftright>, [">= 0.0.3"])
    s.add_dependency(%q<activerecord>, [">= 2.3.0"])
  end
end

